create table AUTHOR (
                        ID bigint generated by default as identity,
                        NAME varchar(255),
                        SECOND_NAME varchar(255),
                        primary key (ID)
);
--
-- create table AUTHOR_GENRES (
--                                FK_AUTHOR bigint not null,
--                                GENRE varchar(255)
-- );
--
-- create table BOOK (
--                       ID bigint generated by default as identity,
--                       ISBN varchar(255),
--                       ISBN13 varchar(255),
--                       SUBTITLE varchar(255),
--                       TITLE varchar(255),
--                       FK_AUTHOR bigint not null,
--                       FK_PUBLISHER bigint not null,
--                       primary key (ID)
-- );
--
-- create table BOOK_GENRES (
--                              FK_BOOK bigint not null,
--                              GENRE varchar(255)
-- );
--
-- create table PUBLISHER (
--                            ID bigint generated by default as identity,
--                            NAME varchar(255),
--                            primary key (ID)
-- );
--
-- alter table AUTHOR_GENRES
--     add constraint FK_AUTHOR_GENRE
--         foreign key (FK_AUTHOR)
--             references AUTHOR;
--
-- alter table BOOK
--     add constraint FK_BOOK_AUTHOR
--         foreign key (FK_AUTHOR)
--             references AUTHOR;
--
-- alter table BOOK
--     add constraint FK_BOOK_PUBLISHER
--         foreign key (FK_PUBLISHER)
--             references PUBLISHER;
--
-- alter table BOOK_GENRES
--     add constraint FK_BOOK_GENRE
--         foreign key (FK_BOOK)
--             references BOOK;

INSERT INTO PUBLISHER(NAME) VALUES
    ('Blue Box Press')
    ,('Inkyard Press')
    ,('Harperteen')
    ,('Tor Books')
    ,('Scribner')
    ,('Redhook')
    ;